-- =====================================================
-- Development Database Clone Setup for Quick Reset Capability
-- Run this AFTER you have fully deployed Liquibase + dbt to ONLINE_STORE_DB
-- =====================================================

-- ONLINE_STORE_DB is your "golden master" - don't modify it after initial setup!
-- ONLINE_STORE_DEV is your working copy - reset it anytime

-- Create the initial development clone from the master database
CREATE DATABASE IF NOT EXISTS ONLINE_STORE_DEV 
    CLONE ONLINE_STORE_DB
    COMMENT = 'Development database - working copy that can be reset anytime';

-- Grant the same permissions to both roles on the dev database
GRANT USAGE ON DATABASE ONLINE_STORE_DEV TO ROLE LIQUIBASE_ROLE;
GRANT USAGE ON DATABASE ONLINE_STORE_DEV TO ROLE DBT_ROLE;

-- Grant schema permissions on dev
GRANT ALL ON SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE LIQUIBASE_ROLE;
GRANT USAGE ON SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE DBT_ROLE;

GRANT ALL ON SCHEMA ONLINE_STORE_DEV.DBT TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA ONLINE_STORE_DEV.DBT TO ROLE LIQUIBASE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE LIQUIBASE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE LIQUIBASE_ROLE;

-- Grant future object permissions on dev
GRANT ALL ON FUTURE TABLES IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE LIQUIBASE_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE LIQUIBASE_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ONLINE_STORE_DEV.PUBLIC TO ROLE DBT_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE LIQUIBASE_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ONLINE_STORE_DEV.DBT TO ROLE LIQUIBASE_ROLE;

-- Show the results
SHOW DATABASES LIKE '%ONLINE_STORE%';